# name: My First Workflow
# on:
#   push:
#   pull_request:
#   schedule:
#     - cron: "23 15 * * *"
# jobs:
#   say-hello:  #job name
#     runs-on: ubuntu-latest  #os on which job will run

#     steps:
#       - name: Print message
#         run: echo "Hello, Github Actions!"
#       - name: Print name
#         run: echo "Sanam"
#   say-bye:
#     runs-on: ubuntu-latest
#     steps:
#       - name: print message
#         run: echo "Good bye from second job" 
# name: needs_keyword
# on: push
# jobs:
#   run-test:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "test is running"
#       - run: echo "test successfull"
#   deploy-app:
#     needs: run-test
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "deployed succesfully"

name: Actions
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout node
        uses: actions/checkout@v4
      # - name: list file
      #   run: ls
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Check node version
        run: node -v
      - name: check npm version
        run: npm -version
